spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MySql;DB_CLOSE_DELAY=-1
    username:
    password:
    driver-class-name: org.h2.Driver


  jpa:
    generate-ddl: false
    show-sql: true
    format_sql: false
    properties:
      hibernate.session_factory.interceptor: com.pismery.study.interceptor.JpaInterceptor
    hibernate:
      ddl-auto: update #none, validate, update, create, and create-drop.
      # org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl：不做修改，直接映射
      # org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy:在进行领域映射时,首字母小写，大写字母变为下划线加小写
      #//ex: LoginName --> login_name
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      #org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
      #org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      #org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
      #org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
      #org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

log:
  path: ./export/logs
logging:
  level:
    com.pismery.study.interceptor: debug
    com.pismery.study.service: debug
#    org.springframework: debug